### ISSUE TITLE
insecure-registries参数没有生效

### ISSUE THREAD

**Issue by likakuli** [alibaba/Dragonfly#138]
docker的daemon.config文件中配置了"insecure-registries":["10.0.13.19"]，用harbor搭的本地私有仓储，通过http-proxy的方式使用的蜻蜓，dfdaemon --registry http://10.0.13.19

docker版本： 17.09.0
蜻蜓版本：
supernode: 0.2.0
dfdaemon: 0.2.0

结果：
docker login 10.0.13.19失败
提示：Error response from daemon: Login: Account is not active. Please see the documentation of the registry http://10.0.13.19/v1/ for instructions how to activate it.

查看docker日志，一直在访问https的api
:09.596326606+08:00" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://10.0.13.19/v2/: Not Found"
:09.598108333+08:00" level=info msg="Error logging in to v2 endpoint, trying next endpoint: login attempt to http://10.0.13.19/v2/ failed with statu
:09.598645528+08:00" level=info msg="Error logging in to v1 endpoint, trying next endpoint: Get https://10.0.13.19/v1/users/: Not Found"

看起来很像是insecure-registries参数没有生效，但是把dfdaemon降为0.0.1版本就没问题了，0.0.1版本的时候叫df-daemon

**Comment by likakuli** [comment]
而且耗时比直接docker pull耗时高，默认的同时拉三层，但看起来同时只拉一层，没有并发，而且在一层拉完再拉下一层的时候有明显的卡顿

**Comment by xunchangguo** [comment]
我用的0.2.0版本，现象和你的一样，我还试过http_proxy方式，都没成功

**Comment by mdchao2010** [comment]
你好 参照你的[blog](http://likakuli.com/post/2018/09/13/dragonfly/)搭建的，遇到以下问题，
df-daemon -v
0.0.1
docker version
Client:
 Version:      17.09.0-ce
supernode 0.2.0

dfclient log:
```
ERROR sign:13352-1550539510.346 lineno:136 : init fail but try back down
Traceback (most recent call last):
  File "/opt/df-client/dfget", line 128, in <module>
    register_result = env.init()
  File "/opt/df-client/env.py", line 148, in init
    paramparser.cmdparam.identifier)
  File "/opt/df-client/env.py", line 84, in register
    nodes, paramparser.cmdparam.url, task_url, port, http_path, md5, identifier)
  File "/opt/df-client/component/httputil.py", line 86, in register
    raise Exception("register result:%s" % result)
Exception: register result:{u'code': 607}

```
dfserver.log
```
 checking alive
[2019-02-18 17:25:08,938] INFO sign:13308-1550539508.923 lineno:89 : start server gc
[2019-02-18 17:25:08,942] INFO sign:13308-1550539508.923 lineno:235 : read port finish from pipe
[2019-02-18 17:25:08,947] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:08,949] INFO sign:13308-1550539508.923 lineno:248 : service port:33465 and pid:13333
[2019-02-18 17:25:08,968] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:08,969] INFO sign:13309-1550539508.953 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:08,969] INFO sign:13309-1550539508.953 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:08,977] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:08,979] INFO sign:13307-1550539508.969 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:08,979] INFO sign:13307-1550539508.969 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:08,996] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:08,997] INFO sign:13312-1550539508.975 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:08,997] INFO sign:13312-1550539508.975 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:10,359] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:10,360] INFO sign:13352-1550539510.346 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:10,360] INFO sign:13352-1550539510.346 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:10,369] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:10,370] INFO sign:13351-1550539510.351 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:10,370] INFO sign:13351-1550539510.351 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:10,388] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:10,389] INFO sign:13349-1550539510.361 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:10,396] INFO sign:13349-1550539510.361 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:10,471] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:10,472] INFO sign:13353-1550539510.466 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:10,472] INFO sign:13353-1550539510.466 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:25:11,368] INFO sign:13308-1550539508.923 lineno:417 : update total limit to 20971520
[2019-02-18 17:25:11,368] INFO sign:13386-1550539511.358 lineno:182 : reuse exist service with port:33465
[2019-02-18 17:25:11,368] INFO sign:13386-1550539511.358 lineno:248 : service port:33465 and pid:-1
[2019-02-18 17:30:11,384] INFO sign:13308-1550539508.923 lineno:137 : acquire checker lock
[2019-02-18 17:30:11,388] INFO sign:13308-1550539508.923 lineno:150 : release checker lock
[2019-02-18 17:30:11,388] INFO sign:13308-1550539508.923 lineno:152 : acquire gc lock
[2019-02-18 17:30:11,388] INFO sign:13308-1550539508.923 lineno:154 : server down

```

**Comment by seamounts** [comment]
dfdaemon 0.3.0 无法使用 harbor。换成 0.0.1 版本可以，这个怎么解决

**Comment by seamounts** [comment]
对接harbor发现的问题：
1. 使用 registry-mirrors 配置后，拉取 harbor 镜像没有经过 Dragonfly.
2. 配置 通过http-proxy 模式使用，发现 insecure-registries参数不生效，登陆拉取均报 403
3. 目前发现在 http-proxy 模式下，使用 0.0.1 版本dfdaemon 可以正常登陆，但拉取镜像偶尔会报 504

**Comment by allencloud** [comment]
@seamounts 详细的报错信息，可以贴上来吗？

**Comment by seamounts** [comment]
> 而且耗时比直接docker pull耗时高，默认的同时拉三层，但看起来同时只拉一层，没有并发，而且在一层拉完再拉下一层的时候有明显的卡顿

遇到了同样情况，用 df-client 拉取反而更慢了

**Comment by seamounts** [comment]
> @seamounts 详细的报错信息，可以贴上来吗？
1. 对接harbor 时， 配置 registry-mirrors 后，拉取镜像没有经过 Dragonfly，看日志没有错误信息
2. 使用 http-proxy 后， 登陆 harbor 报错如下：
 Error response from daemon: login attempt to http://10.21.66.18/v2/ failed with status: 403 Forbidden
3. 报504 那个错误是配置问题，已经解决了。
目前使用 http-proxy  模式 加 0.0.1 版本 dfdaemon 可以正常拉取。0.0.1以上的版本都不行

**Comment by khchan123** [comment]
Yes. I am seeing the same problem too. I use dfclient 0.3.0 + Harbor (HTTP only). I configured Dragonfly as HTTP_PROXY, but it's not working and always getting HTTP403 error. Any help is appreciated?

```

[kchan@kchan04 ~]$ dfdaemon --registry=192.168.0.104 &
[kchan@kchan04 ~]$ cat /etc/docker/daemon.json 
{
  "insecure-registries": [
    "127.0.0.1:65001",
    "192.168.0.104"
  ]
}
```


```
[kchan@kchan04 ~]$ docker pull 192.168.0.104/library/hello-world
Using default tag: latest
Error response from daemon: error parsing HTTP 403 response body: invalid character 'o' in literal null (expecting 'u'): "no matched registry for 192.168.0.104"
```

I have capture the HTTP traffic and appears like the dfdaemon does not try to obtain an Bearer Auth token upon HTTP401 error.

![image](https://user-images.githubusercontent.com/50619735/57689895-09d85580-7673-11e9-83ca-29ad0ba8cf43.png)

**Comment by khchan123** [comment]
@allencloud  Do you have any ideas? Do you need more info?

**Comment by lijianfeng1993** [comment]
看看你的harbor.cfg配置文件呢，域名需要配置成地址的。我通常是域名写成registrytest，然后在客户端的/etc/hosts里面加上registrytest
